name: CI/CD Pipeline
on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  TF_VERSION: 0.14.9
  TF_INIT_CLI_OPTIONS: -input=false
  TF_CLI_OPTIONS: -input=false -auto-approve
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
    - name: Terraform Init
      run: terraform init ${{ env.TF_INIT_CLI_OPTIONS }}
    - name: Terraform Plan
      run: terraform plan ${{ env.TF_CLI_OPTIONS }}
    - name: Terraform Apply
      run: terraform apply ${{ env.TF_CLI_OPTIONS }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: |
        python -m unittest discover -s tests
    - name: Deploy
      run: |
        # Add your deployment commands here
        echo "Deploying application"
    - name: Error Handling
      if: failure()
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/{owner}/{repo}/issues
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        title: Deployment failed
        body: The deployment failed. Please check the actions log.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}