name: CI/CD Pipeline
on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.9.x
  TF_WORKING_DIR: .
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
    - name: Terraform Init
      run: terraform init -input=false ${{ env.TF_WORKING_DIR }}
    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan ${{ env.TF_WORKING_DIR }}
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
  build-test-deploy:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: pytest
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.terraform.outputs.public_ip }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /path/to/app
          git pull
          systemctl restart flask-app
  error_handling:
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - name: Create GitHub issue
      uses: actions/github-script@v6
      with:
        script: |
          const issue = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "CI/CD pipeline failed",
            body: `Run ID: ${context.runId}\n\nLogs: https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
          };
          github.issues.create(issue);